2025-06-30 23:55:14,916 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.10.21.185:5000
2025-06-30 23:55:14,919 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-06-30 23:55:23,293 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:23] "GET / HTTP/1.1" 200 -
2025-06-30 23:55:23,719 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:23] "GET /static/css/custom.css HTTP/1.1" 200 -
2025-06-30 23:55:23,719 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:23] "GET /static/js/custom.js HTTP/1.1" 200 -
2025-06-30 23:55:32,209 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:32] "GET /login HTTP/1.1" 200 -
2025-06-30 23:55:32,329 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:32] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:55:32,347 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:32] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:55:35,788 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:35] "GET /register HTTP/1.1" 200 -
2025-06-30 23:55:35,806 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:35] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:55:35,811 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:35] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:55:39,934 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:39] "GET /login HTTP/1.1" 200 -
2025-06-30 23:55:39,993 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:39] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:55:40,006 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:55:40] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:56:43,751 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\MedTrack-Healthcare-App-main\MedTrack-Healthcare-App-main\app.py", line 193, in login
    user = user_table.get_item(Key={'email': email}).get('Item')
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 601, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1056, in _make_api_call
    http, parsed_response = self._make_request(
                            ~~~~~~~~~~~~~~~~~~^
        operation_model, request_dict, request_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1080, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        event_name,
        ^^^^^^^^^^^
        request=request,
        ^^^^^^^^^^^^^^^^
        operation_name=operation_model.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 108, in handler
    return self.sign(operation_name, request)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 200, in sign
    auth.add_auth(request)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\auth.py", line 421, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2025-06-30 23:56:43,926 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:43] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
2025-06-30 23:56:43,983 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:43] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:56:43,986 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:43] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:56:50,774 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:50] "GET / HTTP/1.1" 200 -
2025-06-30 23:56:50,838 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:50] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:56:50,840 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:50] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:56:56,729 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:56] "GET /login HTTP/1.1" 200 -
2025-06-30 23:56:56,789 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:56] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:56:56,800 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:56:56] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:57:00,469 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:00] "GET /register HTTP/1.1" 200 -
2025-06-30 23:57:00,533 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:00] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:57:00,538 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:00] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:57:41,688 - app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\MedTrack-Healthcare-App-main\MedTrack-Healthcare-App-main\app.py", line 153, in register
    existing_user = user_table.get_item(Key={'email': email}).get('Item')
                    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 601, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1056, in _make_api_call
    http, parsed_response = self._make_request(
                            ~~~~~~~~~~~~~~~~~~^
        operation_model, request_dict, request_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1080, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        event_name,
        ^^^^^^^^^^^
        request=request,
        ^^^^^^^^^^^^^^^^
        operation_name=operation_model.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 108, in handler
    return self.sign(operation_name, request)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 200, in sign
    auth.add_auth(request)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\auth.py", line 421, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2025-06-30 23:57:41,707 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:41] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
2025-06-30 23:57:41,730 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:41] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:57:41,732 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:41] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:57:48,152 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:48] "GET / HTTP/1.1" 200 -
2025-06-30 23:57:48,212 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:48] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:57:48,221 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:48] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:57:55,565 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:55] "GET /login HTTP/1.1" 200 -
2025-06-30 23:57:55,628 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:55] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:57:55,634 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:55] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-06-30 23:57:56,547 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:56] "GET /register HTTP/1.1" 200 -
2025-06-30 23:57:56,603 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:56] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-06-30 23:57:56,611 - werkzeug - INFO - 127.0.0.1 - - [30/Jun/2025 23:57:56] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:40:06,162 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.10.21.185:5000
2025-07-01 02:40:06,163 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-01 02:40:39,792 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:40:39] "GET / HTTP/1.1" 200 -
2025-07-01 02:40:40,475 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:40:40] "GET /static/css/custom.css HTTP/1.1" 200 -
2025-07-01 02:40:40,524 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:40:40] "GET /static/js/custom.js HTTP/1.1" 200 -
2025-07-01 02:40:50,076 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:40:50] "GET /register HTTP/1.1" 200 -
2025-07-01 02:40:50,109 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:40:50] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-07-01 02:40:50,112 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:40:50] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:41:08,463 - app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\MedTrack-Healthcare-App-main\MedTrack-Healthcare-App-main\app.py", line 153, in register
    existing_user = user_table.get_item(Key={'email': email}).get('Item')
                    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 601, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1056, in _make_api_call
    http, parsed_response = self._make_request(
                            ~~~~~~~~~~~~~~~~~~^
        operation_model, request_dict, request_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1080, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        event_name,
        ^^^^^^^^^^^
        request=request,
        ^^^^^^^^^^^^^^^^
        operation_name=operation_model.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 108, in handler
    return self.sign(operation_name, request)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 200, in sign
    auth.add_auth(request)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\auth.py", line 421, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2025-07-01 02:41:08,605 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:41:08] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
2025-07-01 02:41:08,656 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:41:08] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:41:08,658 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:41:08] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-07-01 02:42:02,619 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:02] "GET / HTTP/1.1" 200 -
2025-07-01 02:42:02,815 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:02] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-07-01 02:42:02,817 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:02] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:42:07,263 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:07] "GET /register HTTP/1.1" 200 -
2025-07-01 02:42:07,318 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:07] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-07-01 02:42:07,335 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:07] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:42:25,465 - app - ERROR - Exception on /register [POST]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\MedTrack-Healthcare-App-main\MedTrack-Healthcare-App-main\app.py", line 153, in register
    existing_user = user_table.get_item(Key={'email': email}).get('Item')
                    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 601, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1056, in _make_api_call
    http, parsed_response = self._make_request(
                            ~~~~~~~~~~~~~~~~~~^
        operation_model, request_dict, request_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1080, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        event_name,
        ^^^^^^^^^^^
        request=request,
        ^^^^^^^^^^^^^^^^
        operation_name=operation_model.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 108, in handler
    return self.sign(operation_name, request)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 200, in sign
    auth.add_auth(request)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\auth.py", line 421, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2025-07-01 02:42:25,507 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:25] "[35m[1mPOST /register HTTP/1.1[0m" 500 -
2025-07-01 02:42:25,554 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:25] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-07-01 02:42:25,563 - werkzeug - INFO - 127.0.0.1 - - [01/Jul/2025 02:42:25] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:45:08,482 - werkzeug - INFO - [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://10.10.21.185:5000
2025-07-01 02:45:08,484 - werkzeug - INFO - [33mPress CTRL+C to quit[0m
2025-07-01 02:45:25,982 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:25] "GET / HTTP/1.1" 200 -
2025-07-01 02:45:26,448 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:26] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:45:26,454 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:26] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-07-01 02:45:36,985 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:36] "GET /login HTTP/1.1" 200 -
2025-07-01 02:45:37,020 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:37] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
2025-07-01 02:45:37,027 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:37] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:45:49,377 - app - ERROR - Exception on /login [POST]
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\flask\app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "C:\Users\user\Downloads\MedTrack-Healthcare-App-main\MedTrack-Healthcare-App-main\app.py", line 193, in login
    user = user_table.get_item(Key={'email': email}).get('Item')
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\factory.py", line 581, in do_action
    response = action(self, *args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\boto3\resources\action.py", line 88, in __call__
    response = getattr(parent.meta.client, operation_name)(*args, **params)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 601, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\context.py", line 123, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1056, in _make_api_call
    http, parsed_response = self._make_request(
                            ~~~~~~~~~~~~~~~~~~^
        operation_model, request_dict, request_context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\client.py", line 1080, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 196, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\endpoint.py", line 132, in create_request
    self._event_emitter.emit(
    ~~~~~~~~~~~~~~~~~~~~~~~~^
        event_name,
        ^^^^^^^^^^^
        request=request,
        ^^^^^^^^^^^^^^^^
        operation_name=operation_model.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 108, in handler
    return self.sign(operation_name, request)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\signers.py", line 200, in sign
    auth.add_auth(request)
    ~~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python313\Lib\site-packages\botocore\auth.py", line 421, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
2025-07-01 02:45:49,422 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:49] "[35m[1mPOST /login HTTP/1.1[0m" 500 -
2025-07-01 02:45:49,465 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:49] "[36mGET /static/js/custom.js HTTP/1.1[0m" 304 -
2025-07-01 02:45:49,467 - werkzeug - INFO - 10.10.21.185 - - [01/Jul/2025 02:45:49] "[36mGET /static/css/custom.css HTTP/1.1[0m" 304 -
